## 下载 numpy

使用 pip 下载 numpy

```bash
pip install numpy
```

如果已经下载了 Anaconda，那么在 base 环境下默认下载好了 numpy。当然我们也可以创建一个新的环境来安装 numpy，下面我们设置新环境的名称为 numpy

```bash
conda create -n numpy python=3.7
```

接着激活创建的新环境

```bash
conda activate numpy
```

在新环境下安装 numpy

```bash
conda install numpy
```

然后就可以在新环境下使用 numpy 了。

In [1]:
import numpy as np

## ndarray

numpy 使用的是 ndarray 的数据类型来保存数据的，所谓的 ndarray 表示的是 N-Dimension-Array，即 N 维数组，所以 numpy 可以很方便的来表示多维的数据，接下来将介绍如何创建 ndarray 对象，如何访问 ndarray 对象，以及 ndarray 的相关属性。

### 创建 ndarray 对象

#### arange

使用 arange 来创建对象，该方法接收的参数如下

- start
- stop
- step

该方法的作用是从 start 开始，以 stop 结束，产生以 step 为间距的一系列数。其中 start 和 step 为可选值，默认值分别为 0 和 1，例如

In [2]:
np.arange(5)

array([0, 1, 2, 3, 4])

上面的 arange(5)，相当于是 arange(0, 5, 1)，从 0 开始，以 5 结束，步进为 1，产生一系列数，所以 arange(5) 产生的数为 [0, 1 ,2, 3, 4]，结果不包括 5，上面产生的结果的范围是左闭右开的，即 [start, stop)，下面我们来看几个例子

In [3]:
np.arange(1, 3)

array([1, 2])

In [4]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [5]:
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

我们可以通过 numpy 的 info 方法来查看 numpy 方法的具体信息，如

In [6]:
np.info(np.arange)

arange([start,] stop[, step,], dtype=None)

Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range` function, but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, the results will often not
be consistent.  It is better to use `numpy.linspace` for these cases.

Parameters
----------
start : number, optional
    Start of interval.  The interval includes this value.  The default
    start value is 0.
stop : number
    End of interval.  The interval does not include this value, except
    in some cases where `step` is not an integer and floating point
    round-off affects the length of `out`.
step : number, optional
    Spacing between values.  For any output `out`, this is the distance
    between two adjacent values, ``out[i+1] - out[i]``

#### linspace

接下来下面我们介绍使用 linspace 来创建 ndarray 对象。该函数的作用是将给定的区间均匀的划分为 N 等份，所以最基本的应该有两个参数来给定区间大小，分别为 start 和 stop，当不给定 N 时，默认划分为 50 份

In [8]:
np.linspace(0, 49)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.])

我们可以通过参数 num 来指定划分为多少份

In [9]:
np.linspace(0, 10, num=11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

通过上面的例子我们发现，我们得到的数组它的范围在 [start, stop] 之间，即左右都是封闭的，我们可以通过传入 endpoint 来改变这个行为，它是一个布尔值，当值为 True 时表示包含 stop，为 False 时表示不包含 stop，默认值为 True，我们修改 endpoint 为 False 来看下结果

In [10]:
np.linspace(0, 10, num=11, endpoint=False)

array([0.        , 0.90909091, 1.81818182, 2.72727273, 3.63636364,
       4.54545455, 5.45454545, 6.36363636, 7.27272727, 8.18181818,
       9.09090909])

上面得到的数组元素之间的间隔 step 是自动计算得到的，如果我们希望能够得到 step 的大小，我们可以通过传入 retstep 的值为 True 来得到 step 值，这个时候 linspace 会返回一个元祖，元祖的第一个元素就是 ndarray 对象，第二个元素就是 step 值

In [11]:
np.linspace(0, 10, 11, retstep=True)

(array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)

#### array

array 方法它的作用就是将一个类数组(array_like) 变为一个 ndarray 对象，比如将 list 变为一个 ndarray 对象

In [13]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

关于 array 方法，知道这么多就够用了，如果想了解更加详细的信息，那就通过 np.info 查看。

####  ones和zeros

下面介绍两个方法来创建元素全 1 和全 0 的数组，它们分别是 ones 和 zeros，它们都需要接收一个表示形状的元祖参数，来决定输出 ndarray 对象的形状

In [16]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.zeros((10,))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((10, 1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [19]:
np.zeros((1, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### 访问 ndarray 对象

我们完全可以将 ndarray 看做是 list，我们可以通过 [index] 的形式来访问 ndarray 对象中的元素，当然我们也可以通过切片的方式来访问

In [20]:
# 生成符合均值为 0， 方差为 1 的正态分布的随机数，个数为 10 * 10
b = np.random.normal(0, 1, (10, 10))

print(b)

[[ 0.06919573 -0.24188977 -0.68455416 -2.07068023  2.80243371 -0.42935685
   0.11773026 -2.06743583  0.44219591  0.11982165]
 [-0.14465873 -0.15037763  0.33420661  0.01945726 -0.5263156   0.88381734
  -0.5609567  -0.10305659 -0.48146344 -0.67208818]
 [ 1.23150149 -1.21189511 -0.48193308  0.64763366  1.03340506  0.87124056
  -1.2152535   1.40643233  1.35749941  0.30754234]
 [-0.57931491 -0.55621786  1.12457391  0.16242107 -1.36883925 -0.95126884
  -0.87279687  0.38494399 -0.18119258  0.59474948]
 [ 0.76893136 -1.23505979  0.7093187  -0.68116596 -1.74445026  0.18380907
   0.67332016  0.22392547 -1.21848506 -0.36607592]
 [-1.45639629  0.31094321  1.19307513 -1.87139056 -0.33479409  2.50316347
  -0.76524934  0.00775338  0.47245051  1.07585657]
 [ 0.03777429 -0.72992872  0.54710717  0.09034676 -2.7283     -1.39820113
   0.95392062 -1.81650025  1.73727875  0.98560116]
 [-0.6072326  -0.14660564 -0.37108136 -0.3839672  -0.14923606  0.3421356
  -0.71619792 -0.26358501 -0.13848647  0.15698095]
 

In [21]:
b[0] # 第一行

array([ 0.06919573, -0.24188977, -0.68455416, -2.07068023,  2.80243371,
       -0.42935685,  0.11773026, -2.06743583,  0.44219591,  0.11982165])

In [22]:
b[0, 2] # 相当于 b[0][2]，获得第一行，第三列的数据

-0.6845541644217675

In [23]:
b[0, -1] # 获得第一行，最后一列的数据，-1表示倒数第一个

0.11982164559424706

In [24]:
b[0: 3] # 获得第一行到第四行的数据，不包括第四行

array([[ 0.06919573, -0.24188977, -0.68455416, -2.07068023,  2.80243371,
        -0.42935685,  0.11773026, -2.06743583,  0.44219591,  0.11982165],
       [-0.14465873, -0.15037763,  0.33420661,  0.01945726, -0.5263156 ,
         0.88381734, -0.5609567 , -0.10305659, -0.48146344, -0.67208818],
       [ 1.23150149, -1.21189511, -0.48193308,  0.64763366,  1.03340506,
         0.87124056, -1.2152535 ,  1.40643233,  1.35749941,  0.30754234]])

In [25]:
b[0: 3, -1] # 获得第一行到第四行最后一列的数据

array([ 0.11982165, -0.67208818,  0.30754234])

### ndarray 对象的属性

下面介绍 ndarray 对象拥有的属性，包括

- size：ndarray 对象中有多少个元素
- shape：ndarray 对象的形状
- dtype：ndarray 对象保存元素的类型
- ndim：ndarray 对象的维度
- T：ndarray 对象的转置
- flat：保存 ndarray 展成一维形状的迭代对象

In [26]:
a = np.array([[1, 2, 3], [4, 5, 6],  [7, 8, 9]])

print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
a.size

9

In [28]:
a.shape

(3, 3)

In [29]:
a.dtype

dtype('int32')

In [30]:
a.ndim

2

In [31]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [32]:
flat_iterator = a.flat

for i in flat_iterator:
    print(i)

1
2
3
4
5
6
7
8
9


上面介绍的属性都是很容易理解的，在这里补充一点优点 dtype 的知识。其实在上面很多介绍的方法中，我们都可以传入一个 dtype 参数来指定使用什么数据类型来保存元素，如果不指定的话，那么会根据输入的元素来自动的推定使用哪种数据类型保存元素。

那 numpy 为我们提供了哪些数据类型呢? 如下

| 数据类型 | 简介|
| --- | --- |
| int8 | 使用8位保存整数 |
| int16 | 16 位 |
| int32 | 32 位|
| int64 | 64 位 |
| float16 | 使用 16 位保存浮点数 |
| float32 | 32 位 |
| float64 | 64 位 |
| complex64 | 使用 64 为来保存复数  |
| complex128 | 128 位 |